### ISSUE TITLE
Many posts cannot be viewed

### ISSUE THREAD

**Issue by aaroncommand** [mrusme/superhighway84#10]
Love this project! About a half hour after installing and running it, I still can't view a lot of the posts - specifically the older ones that from their subject lines appear to be reposts of news articles (e.g. Anti-mimetic tactics for living a counter-cultural life, Gene Therapy for a Failing Heart).

The body of these posts just shows up as "NA."

I am using the linux binary release on Ubuntu 21.04 with ipfs installed from the snap repository.

When I start the client I get the warning `failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.` Maybe these are longer posts and this is somehow related?

**Comment by mrusme** [comment]
Hehe, sorry for the confusion there. These are old posts I made for testing purposes. NA is the whole body. :-) I should have known better I guess.

You should be able to see all posts. The warning is known, under the link you can find out what to do to get rid of it. :)
