### ISSUE TITLE
Limit number of connections

### ISSUE THREAD

**Issue by mrusme** [mrusme/superhighway84#14]
It has been reported that the number of connections IPFS creates makes it tricky to run Superhighway84 on especially older hardware.

It was mentioned that apparently this is [a known issue](https://github.com/ipfs/go-ipfs/issues/3320) in IPFS:

> The libp2p team is currently refactoring the "dialer" system in a way that'll make it easy for us to configure a maximum number of outbound connections. Unfortunately, there's really nothing we can do about inbound connections except kill them as soon as we can. On the other hand, having too many connections usually comes from dialing.

I couldn't find out what the status of the libp2p refactoring is though. However, people are mentioning that disabling QUIC in the IPFS repository has helped a bit with the issue, e.g.:

> ... `ipfs init --profile server`, and (3) I removed the lines of quic under `Addresses.Swarm` in `~/.ipfs/config`.

and

> I fust followed the advice here of disabling QUIC
> `ipfs config --json Swarm.Transports.Network.QUIC false`

Another idea could be to try and *press* Superhighway84 into a set of iptables rules that limit its available bandwidth and the amount of connections artificially. I didn't investigate whether that really works, but apparently [other users](https://github.com/ipfs/go-ipfs/issues/6117#issuecomment-612658616) have done that for IPFS.

**Comment by Jay4242** [comment]
It's a pretty serious problem.  Anything over 2,000 peers makes it unusable on some hosts.
Why does it seem to ignore the highwater so much?
I have it set to 10.  It's going into 2,000.
This is also the only time I see https://github.com/mrusme/superhighway84/issues/3 and other errors.
OOM killer comes hunting it at that point.

**Comment by mrusme** [comment]
Currently digging through the IPFS godocs to see if I can find anything. Right now I'm looking at the [Swarm.ConnMgr](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmconnmgr) and trying to figure out if for some reason "none" might be set for Superhighway84 - which I don't believe, though, as the default is "basic" and I didn't remember to have messed around with that.

**Comment by mrusme** [comment]
@Jay4242 just an idea, but can you try running the official IPFS daemon on the very same repo and see how that acts over a longer period of time? E.g. if the OOM killer also at some point triggers and how connections behave there.

**Comment by Jay4242** [comment]
It did calm down a bit, there was an initial spike up to 2k then if it survived that it went lower. ~200-600 peers.
When I run the ipfs daemon in that path and run ipfs swarm peers | wc -l in a loop it does spike into the hundreds initially then drop down to ~10-20.
Maybe a separate issue, but a screen re-draw key combination could be handy for clearing errors, although reading an article and exiting also clears the screen.

**Comment by mrusme** [comment]
Interesting. I've been running 0.0.4 on a VPS for the whole day now and it didn't crash nor reported any "too many open files" issues.

> Maybe a separate issue, but a screen re-draw key combination could be handy for clearing errors, although reading an article and exiting also clears the screen.

Yeah, unfortunately running tview's `Application.Redraw()` can lead to the whole application freezing, for reasons that I didn't bother to investigate yet.

**Comment by mrusme** [comment]
A few more issues in go-ipfs that _might_ be related:

- https://github.com/ipfs/go-ipfs/issues/8561
- https://github.com/ipfs/go-ipfs/issues/4137
- https://github.com/ipfs/go-ipfs/issues/2489
- https://github.com/ipfs/go-ipfs/issues/3429
- https://github.com/ipfs/go-ipfs/issues/6117
- https://github.com/ipfs/go-ipfs/issues/1482
- https://github.com/ipfs/go-ipfs/issues/6117
- https://github.com/libp2p/go-libp2p-swarm/issues/86
- https://github.com/libp2p/go-libp2p-swarm/pull/81
- https://github.com/libp2p/go-libp2p-swarm/issues/86

**Comment by mrusme** [comment]
Connections seem to be down to little over 300 now. Maybe that's due to the latest change in master or it's simply a time when not many peers are online.

![screenshot_2021-12-29-004829](https://user-images.githubusercontent.com/151967/147631369-9af6dfdb-da5c-4f3a-8cde-c026ea9bfcbd.png)

Also CPU usage and network usage alike are very decent right now.

![screenshot_2021-12-29-004905](https://user-images.githubusercontent.com/151967/147631440-bed13129-410c-4ebf-b5d8-548fd57b4765.png)

**Comment by mrusme** [comment]
@Jay4242 please try setting your IPFS repository to lowpower profile and test with that:

```
ipfs config profile apply lowpower
```

See [this](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md) for more info.

**Comment by Jay4242** [comment]
Seems much better now.  I did have it on lowpower before, even setting it lower.  That's why I was so baffled that it was hitting as high as it was.  
Thanks for the updates!

**Comment by mrusme** [comment]
I will close this issue for now but feel free to comment if things start getting worse again. I also talked to the folks over at ipfs on matrix and it seems that upgrading IPFS from the currently used 0.9.1 version to the latest might also help with performance. However, since a few interfaces have changed, it would require me to update [go-orbit-db](https://github.com/berty/go-orbit-db) which is a bigger task.

**Comment by LynHyper** [comment]
@mrusme Btw, also check the value of GracePeriod, during that time all low and high water values are ignored in order to build up connections; consider lowering the value to decrease the amount of time new connections can form in.
