### ISSUE TITLE
Reformat line length

### ISSUE THREAD

**Issue by mrusme** [mrusme/superhighway84#16]
Not sure how others feel about this, but maybe Superhighway84 should enforce a line length (e.g. 72 or 80) by simply reformatting the text upon submission.

**Comment by apatheticposture** [comment]
I think it would be better to set editors to soft-wrap.  80 columns is a minimal width for consoles but I suspect most people are using terminal emulators on larger screens.

The possible downside is any ASCII-style box drawing or art people may choose to use wouldn't display so well, but I think text and paragraphs should flow nicely using softwrap.

**Comment by mrusme** [comment]
As folks seem to be against enforcing a specific line length I'm going to close this issue.
