### ISSUE TITLE
"too many open files"

### ISSUE THREAD

**Issue by vielmetti** [mrusme/superhighway84#3]
I see one post to `alt.social`, but soon afterwards the system crashes with

```
ERROR┐╔═blockstore══════go-ipfs-blockstore@v0.1.6/blockstore.go:218═════blockstore.AllKeysChan got err: walk failed: open /Users/emv/.ipfs-sh84/blocks: too many open files
```

**Comment by mrusme** [comment]
What does your `ulimit -n` say while you're running it? Was it increased to > 1024? If not, you can try to manually do so , e.g. `ulimit -n 2048`.

**Comment by vielmetti** [comment]
```
> ulimit -n
256

~/src/github.com/mrusme/superhighway84 on master ....................................... at 11:11:49
> ulimit -n 2048
```

system is MacBook pro, 

```
> uname -a
Darwin woodward.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
```

With `ulimit` changed, no errors.

**Comment by mrusme** [comment]
Will check if I can set ulimit on start.

**Comment by mrusme** [comment]
@vielmetti please try setting your IPFS repository to lowpower profile and test with that:

```
ipfs config profile apply lowpower
```

See [this](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md) for more info.

**Comment by mrusme** [comment]
I've tested the above profile on the macbook, as well as two small-scale VPS and they've all been running for the past day with no issues at all. This seems to have more or less fixed this issue. I've documented it already in the README, so people should be go to go.
