### ISSUE TITLE
Redraw TUI shortcut

### ISSUE THREAD

**Issue by smitec** [mrusme/superhighway84#31]
Occasionally errors will post log messages to the terminal. This writes over the top of the TUI. 

Sometimes moving between threads cases a redraw of that area but not always.

It would be handy if refresh (or some other shortcut) allowed a total TUI redraw to clean up after this happens.

I don't have a clearer screenshot as an example but the one attached shows some date info after the download total due to an error message that was printed.

<img width="187" alt="Screen Shot 2022-01-10 at 3 25 08 pm" src="https://user-images.githubusercontent.com/515977/148721590-40e4f464-7a93-4256-a166-12bcab90459c.png">
.

**Comment by mrusme** [comment]
I can't really test this because so far I haven't had any issue popping up and messing with the UI, but I've implemented a [Sync](https://pkg.go.dev/github.com/rivo/tview#Application.Sync) when the refresh shortcut was pressed, which according to its documentation should do what you asked for. :-)
