### ISSUE TITLE
Show Poster and Subject in editor view.

### ISSUE THREAD

**Issue by apatheticposture** [mrusme/superhighway84#36]
Often I lose track.  The article browser shows this info but if an article does not fit in the preview window I open it such that it opens in my editor.  It would be nice to populate the top of the article with the poster and subject as I sometimes lose my place.

**Comment by mrusme** [comment]
As for the author, yes, that's lacking when you open the editor. It can be added.
However, the subject should actually be visible in the editor. Please double-check.
