### ISSUE TITLE
Mix of tabs and spaces

### ISSUE THREAD

**Issue by mprimi** [mrusme/superhighway84#40]
This codebase is a mixture of spaces and tabs.

![sample](https://user-images.githubusercontent.com/6885259/155936094-c3cd1d95-2337-4c73-9441-ca13e5d12944.png)

Would you mind doing a pass and switching everything to one or the other?

(@mrusme I'm surprised you haven't noticed, I'm guessing you don't have invisibles turned on in your editor, and probably use different editors?)

I'd send a PR myself, but I don't want to 'steal' all of these LOCs from you! 🙂
```
$ grep -e  '^\t' *.go */*.go | wc -l
     245
$ grep -e  '^  ' *.go */*.go | wc -l
    1257
```

**Comment by mrusme** [comment]
Thanks Marco, you're correct, it should be spaces everywhere but it seems like [vim-editorconfig](https://github.com/editorconfig/editorconfig-vim) doesn't quite work the way I expected it to do. I will change the lines that have tabs in them.

**Comment by mrusme** [comment]
Correction, the editorconfig plug works, it seems like vim-go is overriding spaces with tabs on save, for example when adjusting the imports. It's basically gofmt forcing what the Go people think is the only acceptable indentation for writing Go code.
