### ISSUE TITLE
[Bug] "initializing TUI and loading database, please wait ..." wait forever

### ISSUE THREAD

**Issue by diyism** [mrusme/superhighway84#42]
```
$ ipfs version
ipfs version 0.12.2

$ git clone --depth 1 https://github.com/mrusme/superhighway84
$ cd superhighway84
$ nano go.mod        #modify ipfs version from "github.com/ipfs/go-ipfs v0.11.0" to "github.com/ipfs/go-ipfs v0.12.2"
$ go mod tidy
$ go build .
$ killall ipfs
$ ./superhighway84
2022/04/16 00:55:38 loading configuration ...
2022/04/16 00:55:38 initializing logger ...
2022/04/16 00:55:38 initializing cache ...
2022/04/16 00:55:38 initializing TUI and loading database, please wait ...

# It seems it will wait forever
```

**Comment by mrusme** [comment]
You're not supposed to modify the deps on your own. Your local IPFS version has basically nothing to do with Superhighway84. Just clone, build and start. Wait a little initially as it takes some time to sync the db.

**Comment by diyism** [comment]
The current code in https://github.com/mrusme/superhighway84 won't work:

```
$ git restore .

$ git log
commit 8802d55663e4821aa47742529fe32c54dbf6ff6b (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: マリウス <marius@xn--gckvb8fzb.com>
Date:   Sun Apr 3 16:01:53 2022 -0500

$ go build .
$ killall ipfs

$ ./superhighway84
2022/04/16 11:30:50 loading configuration ...
2022/04/16 11:30:50 initializing logger ...
2022/04/16 11:30:50 initializing cache ...
2022/04/16 11:30:50 initializing TUI and loading database, please wait ...
2022/04/16 11:30:51 Your programs version (11) is lower than your repos (12).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.
panic: Your programs version (11) is lower than your repos (12).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.


goroutine 1 [running]:
log.Panicln({0xc00260ff48, 0xc0000bb500, 0xc0006a9080})
	/home/malcolm/WorkSpace/forkgo/gosrc/go/src/log/log.go:645 +0x65
main.main()
	/home/malcolm/Downloads/test/superhigh/superhighway84/superhighway84.go:155 +0x5e6
```

**Comment by mrusme** [comment]
Please refer to the `RUNNING` section in the [README.md](README.md). You can find out how to run IPFS alongside Superhighway84 there.

**Comment by mrusme** [comment]
I've created a todo to implement a way for initializing the repo through Superhighway84 in the future.

**Comment by diyism** [comment]
```
$ wget https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.11.1/go-ipfs_v0.11.1_linux-amd64.tar.gz
$ tar xzf go-ipfs_v0.11.1_linux-amd64.tar.gz
$ export IPFS_PATH=~/.ipfs-sh84
$ ./go-ipfs/ipfs init
$ ./superhighway84
#first time, it shows the TUI
#I type ctrl+c  to close it
$./superhighway84
#now it wait forever with "initializing TUI and loading database, please wait ..."
```

**Comment by mrusme** [comment]
Define *forever*. :-) It could take a while for IPFS to sync, indeed. It really depends on the amount of peers. You might give it a few tries at first to see whether that's really not just a latency issue.

When you started it the first time, did you see any content? If not I assume the IPFS repo wasn't synced yet. If you did and now it doesn't come back up, then it's tricky indeed. 🤔

**Comment by mrusme** [comment]
On a side-note, your profile says Shanghai, China. Trying not to be insensitive, but have you tried whether IPFS generally works from your location? Just to make sure it's not blocked. For example, I had a situation while in Spain where IPFS was indeed blocked by the provider.

**Comment by diyism** [comment]
Amazing, it works after waiting for 5 minutes.

![2022-04-17-021536_2560x1688_scrot](https://user-images.githubusercontent.com/1744399/163686825-65387b64-d29c-43e3-9bbb-d034ccf74833.png)

**Comment by mrusme** [comment]
:-) cool, happy to hear!

**Comment by mrusme** [comment]
FYI: go-orbit-db was upgraded to 1.17.1, which now uses go-ipfs 0.12.2. I have just pushed an update, 0.2.0, which includes the updated libraries. Now Superhighway84 is able to run on IPFS 0.12 repositories!

**Comment by diyism** [comment]
Great, than you.
