### ISSUE TITLE
Conversation threading

### ISSUE THREAD

**Issue by mrusme** [mrusme/superhighway84#6]
As more and more people start to use this platform (hehehe :-) 👍🏼 ) conversation threading needs to be implemented in order to enhance the reading experience.

On the back-end, this was already done, with articles having the `InReplyToID` field. What's left to be done is the front-end code in `tui/mainscreen.go`, specifically the `Refresh` function that renders the list.

**Comment by Jay4242** [comment]
Great stuff.  Would it be possible to toggle between the two views?
Then it's like sorting by recent comments vs recent threads.
Maybe even a different option of having comments bump the threads up?

**Comment by mrusme** [comment]
@Jay4242 https://xkcd.com/1172/

However, yes, it would be possible. In its current stage I'd prefer to iterate on multiple things bit by bit, rather than work on one single aspect until it's perfect. :-) I'm sure I'll be going to refactor the code sometime in future and at that point the toggling and sorting could be built in.

Alternatively, if anyone feels like digging into this and try implementing it right away I wouldn't mind a PR, hehe.
