### ISSUE TITLE
Seems to be locked up on Windows? Never fetches groups

### ISSUE THREAD

**Issue by dvasdekis** [mrusme/superhighway84#65]
Have installed Kubo 0.16 as only system install of IPFS, and SH84 v0.2.4, and trying to use it with Powershell 7 x64 7.3.4.

Sadly it just sits and looks like this, for hours:
<img width="661" alt="image" src="https://github.com/mrusme/superhighway84/assets/19279397/6e8828de-e319-4297-b3ac-a2a036fa8512">
I left it overnight and it's still stuck. `Ctrl+r` makes the little thing at the bottom left green for a second, and then back to grey. Pressing `r` without ctrl produces the below output:
```
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        /home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220731115447-9d32d269593e/application.go:243 +0x4d
panic({0x212d1a0, 0xc0084266f0})
        /opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x207
github.com/mrusme/superhighway84/tui.(*Mainscreen).HandleInput(0xc00007b180, 0x285beb8?)
        /home/runner/work/superhighway84/superhighway84/tui/mainscreen.go:355 +0x4e5
github.com/mrusme/superhighway84/tui.(*TUI).initInput.func1(0xc006812b40)
        /home/runner/work/superhighway84/superhighway84/tui/tui.go:143 +0x13e
github.com/rivo/tview.(*Application).Run(0xc0003b8000)
        /home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220731115447-9d32d269593e/application.go:318 +0x782
github.com/mrusme/superhighway84/tui.(*TUI).Launch(0xc00007af00)
        /home/runner/work/superhighway84/superhighway84/tui/tui.go:165 +0xa5
main.main()
        /home/runner/work/superhighway84/superhighway84/superhighway84.go:144 +0x95b
```
I love the idea of the project and I'm happy to do some work. How can I start to debug it?

**Comment by mrusme** [comment]
I've rebooted the VPS that permanently runs a stable Superhighway84 release for others to sync from, please try again. Also, have you tried this? https://github.com/mrusme/superhighway84#connectivity

**Comment by dvasdekis** [comment]
Not sure why, but just giving it another go, worked. I can see the articles now. Thank you, and apologies for the wasted time!

**Comment by mrusme** [comment]
No worries, surely was due to the VPN having had hickups, meaning your client was probably not seeing any active peers.
