### ISSUE TITLE
failed to enable TCP keepalives

### ISSUE THREAD

**Issue by vielmetti** [mrusme/superhighway84#8]
This appeared after I did a successful? post.

```
2021-12-27T22:57:55.466-0500u knERROR	tcp-tpt	go-tcp-transport@v0.2.4/tcp.go:52	failed to enable TCP keepalivemes.mor{"error": "set tcp4 192.168.1.196:4001->135.125.8.109:57940: setsockopt: invalid argument"}
```

Running MacOS on MacBook Air, Apple Silicon.

**Comment by vielmetti** [comment]
Looks like a known issue on Darwin in the underlying library, at

https://github.com/libp2p/go-tcp-transport/commit/c22be72adcf203df41b98d981b029ddc74025cef

**Comment by mrusme** [comment]
> Really, I don't know _what_ was causing this, but there's nothing we can
do about it.

Doesn't sound too promising. Not sure what to do here, sorry.

**Comment by vielmetti** [comment]
I'll close this then - anyone who runs into the same problem might find this report.
